# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 00:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalemployee',
            name='job_title_prev',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
