# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 00:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_data', '0003_auto_20171029_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalemployee',
            name='ai_current_job_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='externalemployee',
            name='ai_previous_job_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
