# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_data', '0005_auto_20171029_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalemployee',
            name='location_prev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
