# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_data', '0006_auto_20171029_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalemployee',
            name='current_company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='externalemployee',
            name='currrent_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
