import sys

try:
    from django.db import models
    from django.contrib.postgres.fields import ArrayField
except  Exception as e:
    print (e)
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

# ExternalEmployee model
class ExternalEmployee(models.Model):

    url                          =            models.CharField(unique=True, max_length=400)
    name                         =            models.CharField(max_length=100)
    type                         =            models.CharField(max_length=100)
    job_title                    =            models.TextField(blank=True, null=True)
    job_title_prev               =            models.TextField(blank=True, null=True)
    company_id                   =            models.IntegerField(blank=True, null=True)
    capacity_rate                =            models.FloatField(blank=True, null=True)
    location                     = ArrayField(models.CharField(max_length=100), blank=True, null=True)
    location_prev                =            models.CharField(max_length=100 , blank=True, null=True)
    skills                       = ArrayField(models.CharField(max_length=100), blank=True, null=True)
    ai_endorsements              = ArrayField(models.IntegerField(), blank=True, null=True)
    experience                   =            models.IntegerField(blank=True, null=True)
    date_created                 =            models.DateTimeField(auto_now_add=True)
    ai_job_started               =            models.CharField(max_length=500 , blank=True, null=True)
    ai_current_working_started   = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_previous_working_started  = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_previous_working_finished = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_current_job_title         = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_previous_job_title        = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_current_company           = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_previous_company          = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_current_locations         = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_previoius_locations       = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_current_working_content   =            models.TextField(blank=True, null=True)
    ai_previous_working_content  =            models.TextField(blank=True, null=True)
    ai_company                   =            models.CharField(max_length=500 , blank=True, null=True)
    ai_interests_current_related = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_interests                 = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_education                 =            models.CharField(max_length=500 , blank=True, null=True)
    ai_previous_education        = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_degree                    =            models.CharField(max_length=500 , blank=True, null=True)
    ai_previous_degree           = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_education_field           =            models.CharField(max_length=500 , blank=True, null=True)
    ai_previous_education_field  = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_education_start           = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_education_finished        = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    ai_self_intro                =            models.TextField(blank=True, null=True)
    ai_volunteer_experience      =            models.TextField(blank=True, null=True)
    recommendation_given         =            models.TextField(blank=True, null=True)
    recommendation_received      =            models.TextField(blank=True, null=True)
    ai_activity_articles         =            models.TextField(blank=True, null=True)
    ai_activity_posts            =            models.TextField(blank=True, null=True)
    ai_activity_liked            =            models.TextField(blank=True, null=True)
    activity_followers           =            models.IntegerField(blank=True, null=True)
    accomplishment_language      = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    accomplishment_course        =            models.TextField(blank=True, null=True)
    accomplishment_project       =            models.TextField(blank=True, null=True)
    accomplishment_certification =            models.TextField(blank=True, null=True)
    accomplishment_organization  =            models.TextField(blank=True, null=True)
    accomplishment_honor         =            models.TextField(blank=True, null=True)
    accomplishment_publication   =            models.TextField(blank=True, null=True)
    accomplishment_patent        =            models.TextField(blank=True, null=True)
    accomplishment_scorer        =            models.TextField(blank=True, null=True)
    is_active                    =            models.CharField(max_length=500 , blank=True, null=True)
    currrent_position            =            models.CharField(max_length=500 , blank=True, null=True)
    current_company              =            models.CharField(max_length=500 , blank=True, null=True)
    most_important_certificate   =            models.CharField(max_length=500 , blank=True, null=True)
    most_important_education     =            models.CharField(max_length=500 , blank=True, null=True)
    facebook_link                =            models.CharField(max_length=500 , blank=True, null=True)
    twitter_link                 =            models.CharField(max_length=500 , blank=True, null=True)
    emails                       = ArrayField(models.CharField(max_length=500), blank=True, null=True)
    all_links                    = ArrayField(models.CharField(max_length=500), blank=True, null=True)

class Meta:
    managed = False
    db_table = 'external_employee'